### ISSUE TITLE
how to keep mogo simple & stable while running by docker-compose up all-in-one method?

### ISSUE THREAD

**Issue by kerneltravel** [shimohq/mogo#76]
when install  by "For Docker" method as [official doc](https://github.com/shimohq/mogo#installation) , the command line termial came out with so many info& error that I can't determine which is the final cause of top-ui-presented-problem, In my case, the web request to  http://localhost:19001  will unstoppablly 301-redirect to http://localhost:19001/user/login/?referer=http%3A%2F%2Flocalhost%3A19001%2Fuser%2Flogin%2F%3Freferer%3Dhttp%253A%252F%252Flocalhost%253A19001%252Fuser%252Flogin%252F%253Freferer%253Dhttp%25253A%25252F%25252Flocalhost%25253A19001%25252Fuser%25252Flogin%25252F%25253Freferer%25253Dhttp%2525253A%2525252F%2525252Flocalhost%2525253A19001%2525252Fuser%2525252Flogin%2525252F%2525253Freferer%2525253Dhttp%252525253A%252525252F%252525252Flocalhost%252525253A19001%252525252Fuser%252525252Flogin%252525252F%252525253Freferer%252525253Dhttp%25252525253A%25252525252F%25252525252Flocalhost%25252525253A19001%25252525252Fuser%25252525252Flogin%25252525252F%25252525253Freferer%25252525253Dhttp%2525252525253A%2525252525252F%2525252525252Flocalhost%2525252525253A19001%2525252525252Fuser%2525252525252Flogin%2525252525252F%2525252525253Freferer%2525252525253Dhttp%252525252525253A%252525252525252F%252525252525252Flocalhost%252525252525253A19001%252525252525252Fuser%252525252525252Flogin%252525252525252F%252525252525253Freferer%252525252525253Dhttp%25252525252525253A%25252525252525252F%25252525252525252Flocalhost%25252525252525253A19001%25252525252525252Fuser%25252525252525252Flogin%25252525252525252F%25252525252525253Freferer%25252525252525253Dhttp%2525252525252525253A%2525252525252525252F%2525252525252525252Flocalhost%2525252525252525253A19001%2525252525252525252Fuser%2525252525252525252Flogin%2525252525252525252F%2525252525252525253Freferer%2525252525252525253Dhttp%252525252525252525253A%252525252525252525252F%252525252525252525252Flocalhost%252525252525252525253A19001%252525252525252525252Fuser%252525252525252525252Flogin%252525252525252525252F%252525252525252525253Freferer%252525252525252525253Dhttp%25252525252525252525253A%25252525252525252525252F%25252525252525252525252Flocalhost%25252525252525252525253A19001%25252525252525252525252Fuser%25252525252525252525252Flogin%25252525252525252525252F%25252525252525252525253Freferer%25252525252525252525253Dhttp%2525252525252525252525253A%2525252525252525252525252F%2525252525252525252525252Flocalhost%2525252525252525252525253A19001%2525252525252525252525252Fuser%2525252525252525252525252Flogin%2525252525252525252525252F%2525252525252525252525253Freferer%2525252525252525252525253Dhttp%252525252525252525252525253A%252525252525252525252525252F%252525252525252525252525252Flocalhost%252525252525252525252525253A19001%252525252525252525252525252F.

If docker-compose.yml can make the out put message not so massive, and only output the error or the only-necessary  message. Or it's hard to find out the true cause .

Here is part of the output:

```
mock_1          | 
mock_1          |     _/_/_/_/    _/_/_/    _/_/   
mock_1          |    _/        _/        _/    _/   
mock_1          |   _/_/_/    _/  _/_/  _/    _/    
mock_1          |  _/        _/    _/  _/    _/     
mock_1          | _/_/_/_/    _/_/_/    _/_/  
mock_1          | 
mock_1          | Welcome to Ego, starting application ...
mock_1          | 
mock_1          | {"lv":"info","ts":1646783004,"msg":"init config","lname":"ego.sys","comp":"core.econf","addr":"/mogo/config/docker.toml"}
mock_1          | {"lv":"info","ts":1646783004,"msg":"read watch","lname":"ego.sys","comp":"core.econf","comp":"file datasource","configFile":"/mogo/config/docker.toml","realConfigFile":"/mogo/config/docker.toml","fppath":"/mogo/config/docker.toml"}
mock_1          | {"lv":"info","ts":1646783004,"msg":"init app","lname":"ego.sys","comp":"app","pid":1,"coreNum":2}
mock_1          | {"lv":"info","ts":1646783004,"msg":"reinit default logger","lname":"ego.sys","comp":"core.elog"}
mock_1          | {"lv":"info","ts":1646783004,"msg":"init trace","lname":"ego.sys","comp":"app"}
mock_1          | {"lv":"info","ts":1646783004,"msg":"start db","lname":"ego.sys","comp":"component.egorm","compName":"mysql.default","addr":"mysql:13306","name":"mocro"}
mock_1          | {"lv":"debug","ts":1646783004,"msg":"ClickHouse","lname":"default.log","step":"ch process","dsn":""}
mock_1          | [clickhouse]host(s)=clickhouse:9000, database=default, username=root
mock_1          | [clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=1, server=0 -> 172.21.0.9:9000
mock_1          | [clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
mock_1          | {"lv":"debug","ts":1646783004,"msg":"ClickHouse","lname":"default.log","step":"ch finish"}
mock_1          | [clickhouse][connect=1][hello] <- ClickHouse 22.2.54455 (UTC)
mock_1          | [clickhouse][connect=1]-> ping
mock_1          | [clickhouse][connect=1][process] <- pong
mock_1          | {"lv":"info","ts":1646783004,"msg":"AuthInit","lname":"default.log","step":"UnmarshalKey","oauthInfos":[{"Typ":"github","ClientId":"","ClientSecret":"","Scopes":["user:email","read:org"],"AuthUrl":"https://github.com/login/oauth/authorize","TokenUrl":"https://github.com/login/oauth/access_token","Enable":true,"EmailAttributeName":"","EmailAttributePath":"","RoleAttributePath":"","AllowedDomains":[],"HostedDomain":"","ApiUrl":"https://api.github.com/user","AllowSignup":true,"Name":"","TlsClientCert":"","TlsClientKey":"","TlsClientCa":"","TlsSkipVerify":false,"TeamIds":[],"AllowedOrganizations":[],"AllowedGroups":null},{"Typ":"gitlab","ClientId":"","ClientSecret":"","Scopes":["api"],"AuthUrl":"https://gitlab.com/oauth/authorize","TokenUrl":"https://gitlab.com/oauth/token","Enable":true,"EmailAttributeName":"","EmailAttributePath":"","RoleAttributePath":"","AllowedDomains":[],"HostedDomain":"","ApiUrl":"https://gitlab.com/api/v4","AllowSignup":true,"Name":"","TlsClientCert":"","TlsClientKey":"","TlsClientCa":"","TlsSkipVerify":false,"TeamIds":[],"AllowedOrganizations":[],"AllowedGroups":null}]}
mock_1          | {"lv":"info","ts":1646783004,"msg":"AuthInit","lname":"default.log","step":"ParseAppAndSubURL","appURL":"http://localhost:19001/","appSubURL":""}
mock_1          | {"lv":"info","ts":1646783004,"msg":"init register job","lname":"ego.sys","comp":"task.ejob","name":"install"}
mock_1          | {"lv":"info","ts":1646783004,"msg":"start ejob","lname":"ego.sys","comp":"task.ejob","name":"install","tid":"598b52039d7bd5c5d6b8511df0d9f43d"}
mock_1          | {"lv":"info","ts":1646783004,"msg":"start  ejob","lname":"ego.sys","comp":"task.ejob","name":"install","tid":"598b52039d7bd5c5d6b8511df0d9f43d","cost":0.014}
mock_1          | {"lv":"error","ts":1646783004,"msg":"access","lname":"ego.sys","comp":"component.egorm","compName":"mysql.default","addr":"mysql:13306","method":"gorm:create","name":"mocro.mogo_base_instance","cost":2.239,"tid":"","event":"error","error":"Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'"}
mock_1          | 
mock_1          | 2022/03/08 23:43:24 /mogo/api/pkg/model/db/instance.go:65 Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'
mock_1          | [9.664ms] [rows:0] INSERT INTO `mogo_base_instance` (`datasource`,`name`,`dsn`,`rule_store_type`,`cluster_id`,`file_path`,`namespace`,`configmap`,`prometheus_target`,`ctime`,`utime`,`dtime`) VALUES ('ch','default-ch','tcp://clickhouse:9000?username=root&password=shimo&read_timeout=10&writer_timeou=10&debug=true',0,0,'','','','',1646783004,1646783004,'0')
mock_1          | panic: 
mock_1          |     msg: start up error: Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'
mock_1          |     loc: /mogo/api/main.go:27
mock_1          | {"lv":"error","ts":1646783004,"msg":"create release error","lname":"default.log","error":"Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'"}
mock_1          | {"lv":"error","ts":1646783004,"msg":"insert to index fail","lname":"default.log","error":"Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'"}
mock_1          | {"lv":"panic","ts":1646783004,"msg":"start up error: Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'","lname":"default.log","stack":"github.com/gotomicro/ego/core/elog.(*Component).Panic\n\t/go/pkg/mod/github.com/gotomicro/ego@v0.8.3-0.20220107063841-9459da2415f1/core/elog/component.go:262\ngithub.com/gotomicro/ego/core/elog.Panic\n\t/go/pkg/mod/github.com/gotomicro/ego@v0.8.3-0.20220107063841-9459da2415f1/core/elog/elog_api.go:42\nmain.main\n\t/mogo/api/main.go:27\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
mock_1          | panic: start up error: Error 1062: Duplicate entry 'ch-default-ch' for key 'uix_datasource_name'
mock_1          | 
mock_1          | goroutine 1 [running]:
mock_1          | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0003de000, {0x0, 0x0, 0x0})
mock_1          | 	/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x446
mock_1          | go.uber.org/zap.(*Logger).Panic(0xc0000caba0, {0xc0000caba0, 0x0}, {0x0, 0x0, 0x0})
mock_1          | 	/go/pkg/mod/go.uber.org/zap@v1.19.1/logger.go:230 +0x59
mock_1          | github.com/gotomicro/ego/core/elog.(*Component).Panic(0xc0004b8e80, {0xc0000caba0, 0x59}, {0x0, 0x0, 0x0})
mock_1          | 	/go/pkg/mod/github.com/gotomicro/ego@v0.8.3-0.20220107063841-9459da2415f1/core/elog/component.go:262 +0xd0
mock_1          | github.com/gotomicro/ego/core/elog.Panic(...)
mock_1          | 	/go/pkg/mod/github.com/gotomicro/ego@v0.8.3-0.20220107063841-9459da2415f1/core/elog/elog_api.go:42
mock_1          | main.main()
mock_1          | 	/mogo/api/main.go:27 +0x178
mysql_1         | 2022-03-08T23:54:53.792590Z 34 [Note] Aborted connection 34 to db: 'mocro' user: 'root' host: '172.21.0.14' (Got an error reading communication packets)
mysql_1         | 2022-03-08T23:54:53.793707Z 35 [Note] Aborted connection 35 to db: 'mocro' user: 'root' host: '172.21.0.14' (Got an error reading communication packets)
mogo_mock_1 exited with code 2
fluent-bit_1    | [2022/03/08 23:54:58] [debug] [input:tail:tail.0] scanning path /var/log/containers/access.log
fluent-bit_1    | [2022/03/08 23:54:58] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /var/log/containers/access.log, inode 461373526
fluent-bit_1    | [2022/03/08 23:54:58] [debug] [input:tail:tail.0] 0 new files found on path '/var/log/containers/access.log'

```

**Comment by kerneltravel** [comment]
the docker ps outputs infos that mogo_mock_1 start failed.
```
# docker ps 
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS                          PORTS                                           NAMES
05e685823440   sevennt/mogo:master                   "/bin/sh -c ./bin/mo…"   20 minutes ago   Up 20 minutes                   9001/tcp, 9003/tcp, 0.0.0.0:19001->19001/tcp    mogo_api_1
cc64923c0031   prom/prometheus:latest                "/bin/prometheus --w…"   20 minutes ago   Up 20 minutes                   0.0.0.0:19004->9090/tcp                         mogo_prometheus_1
7ebfe1b53e8a   fhalim/prom2click:latest              "/usr/local/bin/prom…"   20 minutes ago   Up 20 minutes                   0.0.0.0:19006->9201/tcp                         mogo_prom2click_1
48f081de748c   fluent/fluent-bit:1.8.12              "/fluent-bit/bin/flu…"   20 minutes ago   Up 20 minutes                   0.0.0.0:2020->2020/tcp                          mogo_fluent-bit_1
7b3f0756a536   clickhouse/clickhouse-server:latest   "/entrypoint.sh"         20 minutes ago   Up 20 minutes                   9000/tcp, 0.0.0.0:8123->8123/tcp, 9009/tcp      mogo_clickhouse_1
4de791ae9825   rsmnarts/kowl                         "./kowl"                 20 minutes ago   Up 20 minutes                   0.0.0.0:19002->8080/tcp                         mogo_kowl_1
f497736e24c8   bitnami/kafka:2.8.1                   "/opt/bitnami/script…"   20 minutes ago   Up 20 minutes                   9092/tcp                                        mogo_kafka_1
84c92d2dadc5   sevennt/mogo:master                   "/bin/sh -c './bin/m…"   20 minutes ago   Restarting (2) 18 seconds ago                                                   mogo_mock_1
c015041b44a7   zookeeper                             "/docker-entrypoint.…"   20 minutes ago   Up 20 minutes                   2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp          mogo_zookeeper_1
ec11f3c8e01c   mysql:5.7.37                          "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes                   3306/tcp, 33060/tcp, 0.0.0.0:13306->13306/tcp   mogo_mysql_1
d9c4918ef437   redis:5.0.14-alpine                   "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes                   6379-6380/tcp                                   mogo_redis_1
b0642f65aa86   prom/alertmanager:latest              "/bin/alertmanager -…"   20 minutes ago   Up 20 minutes                   0.0.0.0:19005->9093/tcp                         mogo_alertmanager_1
41c23abda893   nginx                                 "/docker-entrypoint.…"   20 minutes ago   Up 20 minutes                   0.0.0.0:19003->80/tcp                           mogo_nginx_1
```
